/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import application.InterfaceCode;
import application.Functions;
import application.Global;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author carri
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        addSummaryButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        analizeSummaryButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        analizeSummaryButton1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        searchKeywordsButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        invReportButton = new javax.swing.JButton();
        searchAuthorButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        jPanel6.setBackground(new java.awt.Color(153, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addSummaryButton.setBackground(new java.awt.Color(0, 0, 0));
        addSummaryButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        addSummaryButton.setForeground(new java.awt.Color(255, 255, 255));
        addSummaryButton.setText("AGREGAR RESUMEN");
        addSummaryButton.setToolTipText("");
        addSummaryButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addSummaryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addSummaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSummaryButtonActionPerformed(evt);
            }
        });
        jPanel6.add(addSummaryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 146, 170, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paper1.jpg"))); // NOI18N
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 80, 100));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 210, 200));

        jPanel7.setBackground(new java.awt.Color(153, 0, 0));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 21, -1, -1));

        analizeSummaryButton.setBackground(new java.awt.Color(0, 0, 0));
        analizeSummaryButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        analizeSummaryButton.setForeground(new java.awt.Color(255, 255, 255));
        analizeSummaryButton.setText("ANALIZAR RESUMEN");
        analizeSummaryButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        analizeSummaryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        analizeSummaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizeSummaryButtonActionPerformed(evt);
            }
        });
        jPanel7.add(analizeSummaryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 170, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/teacher.png"))); // NOI18N
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        analizeSummaryButton1.setBackground(new java.awt.Color(0, 0, 0));
        analizeSummaryButton1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        analizeSummaryButton1.setForeground(new java.awt.Color(255, 255, 255));
        analizeSummaryButton1.setText("ANALIZAR RESUMEN");
        analizeSummaryButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        analizeSummaryButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        analizeSummaryButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizeSummaryButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(analizeSummaryButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 170, 30));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 210, 200));

        jPanel8.setBackground(new java.awt.Color(153, 0, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchKeywordsButton.setBackground(new java.awt.Color(0, 0, 0));
        searchKeywordsButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        searchKeywordsButton.setForeground(new java.awt.Color(255, 255, 255));
        searchKeywordsButton.setText("BUSCAR POR KEYWORDS");
        searchKeywordsButton.setBorder(null);
        searchKeywordsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchKeywordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchKeywordsButtonActionPerformed(evt);
            }
        });
        jPanel8.add(searchKeywordsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 190, 30));
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 122, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dictionary.jpg"))); // NOI18N
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 100));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 210, 200));

        jPanel9.setBackground(new java.awt.Color(153, 0, 0));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        invReportButton.setBackground(new java.awt.Color(0, 0, 0));
        invReportButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        invReportButton.setForeground(new java.awt.Color(255, 255, 255));
        invReportButton.setText("REPORTE INVENTARIO");
        invReportButton.setBorder(null);
        invReportButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        invReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invReportButtonActionPerformed(evt);
            }
        });
        jPanel9.add(invReportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 170, 30));

        searchAuthorButton.setBackground(new java.awt.Color(0, 0, 0));
        searchAuthorButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        searchAuthorButton.setForeground(new java.awt.Color(255, 255, 255));
        searchAuthorButton.setText("BUSCAR POR AUTOR");
        searchAuthorButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchAuthorButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchAuthorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAuthorButtonActionPerformed(evt);
            }
        });
        jPanel9.add(searchAuthorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/author.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 110, 100));

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 210, 220));

        jPanel10.setBackground(new java.awt.Color(153, 0, 0));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel10.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 18, -1, -1));

        exitButton.setBackground(new java.awt.Color(0, 0, 0));
        exitButton.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("SALIR/GUARDAR INFO");
        exitButton.setBorder(null);
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel10.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 170, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.jpg"))); // NOI18N
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 110, 50));

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 220, 220));

        jPanel12.setBackground(new java.awt.Color(0, 0, 0));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));
        jPanel12.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 51));
        jLabel3.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Metro Mendeley");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 290, 40));
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel12.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 70));

        jPanel3.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 70));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void invReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invReportButtonActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_invReportButtonActionPerformed

    private void addSummaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSummaryButtonActionPerformed
        try {
            Functions fc = new Functions();
            Global.initializeApp();
            fc.access_new_file();
        } catch (IOException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    
        
    }//GEN-LAST:event_addSummaryButtonActionPerformed

    private void analizeSummaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizeSummaryButtonActionPerformed
   
    }//GEN-LAST:event_analizeSummaryButtonActionPerformed

    private void searchKeywordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchKeywordsButtonActionPerformed
        InterfaceCode.openSearchKeyWords();
    }//GEN-LAST:event_searchKeywordsButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed

      
    }//GEN-LAST:event_exitButtonActionPerformed

    private void searchAuthorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAuthorButtonActionPerformed
        // TODO add your handling code here:
        InterfaceCode.openSearchAuthor();
    }//GEN-LAST:event_searchAuthorButtonActionPerformed

    private void analizeSummaryButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizeSummaryButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_analizeSummaryButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSummaryButton;
    private javax.swing.JButton analizeSummaryButton;
    private javax.swing.JButton analizeSummaryButton1;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton invReportButton;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton searchAuthorButton;
    private javax.swing.JButton searchKeywordsButton;
    // End of variables declaration//GEN-END:variables
}
